#! /bin/sh

### BEGIN INIT INFO
# Provides: statusd
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Status daemon
### END INIT INFO

## SETTINGS
#
# statusd directory
COREDIR="/var/core"
# core python file
COREFILE="statusd.py"
# You must use the real autossh binary, not a wrapper.
DAEMON=/usr/bin/python
# User to run under
USER=operuser
GROUP=operuser
#
## END SETTINGS

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

NAME=`basename $0`
PIDFILE=/${COREDIR}/${NAME}.pid
SCRIPTNAME=/etc/init.d/${NAME}
DESC="Core RPC"

test -x $DAEMON || exit 0

#	Function that starts the daemon/service.
d_start() {
	start-stop-daemon --start --quiet \
		--chdir $COREDIR --background \
		--group $GROUP --chuid $USER \
		--exec $DAEMON $COREFILE
}

#	Function that stops the daemon/service.
d_stop() {
	start-stop-daemon --stop --quiet --user $USER --name python \
		|| echo -n " not running"
}


case "$1" in
  start)
	echo -n "Starting $DESC: $NAME"
	d_start
	echo "."
	;;
  stop)
	echo -n "Stopping $DESC: $NAME"
	d_stop
	echo "."
	;;

  restart)
	echo -n "Restarting $DESC: $NAME"
	d_stop
	sleep 1
	d_start
	echo "."
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

exit 0
